#
# Basic settings.
#
# url: http://localhost:4000
# baseurl: ""
url: http://ancorrg.github.io
baseurl: ""
title: ancorrg
description: Trying to learn from my past self.
avatar: /assets/img/ogp.png
# favicon: /favicon.ico
favicon: /assets/img/ogp.png
# language: ja
language: en

#
# Icons
#
icons:
  rss: true
  email:
  github: ancorrg
  bitbucket:
  twitter: ancorrg
  facebook:
  google_plus:
  tumblr:
  behance:
  dribbble:
  flickr:
  instagram: ancorrg
  linkedin: https://www.linkedin.com/in/ancorromero/
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: # full URL
  steam:
  wordpress:
  youtube:

#
# Prettify url.
#
permalink: pretty

#
# Scripts.
#
google_analytics: UA-132060897-1
disqus:

#
# Localizations.
#
str_next: Next
str_prev: Prev
str_read_more: Read more...
str_search: Search
str_recent_posts: Recent posts
str_show_all_posts: Show all posts

#
# Recent posts.
#
recent_posts_num: 10

#
# Pagination.
#
paginate: 10
paginate_path: page/:num

#
# Social.
#
share_buttons:
  twitter: true
  facebook: false # needs ogp.fb.app_id
  hatena: false
ogp:
  image_url:
  fb:
    admin: # facebook admin id
    app_id: # facebook application id

#
# Plugins.
#
gems:
  - jekyll-paginate
  - jekyll-feed
  - jemoji

#
# Styles: see "_sass/base/_variables.scss"
#

#
# !! Danger zone !!
#

include: ["_pages"]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
